name: 1 Basic Docker Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      # Set up QEMU is a command used to set up QEMU, which is a generic and open source machine emulator and virtualizer.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          # this is a list of platforms that QEMU will be set up for.
          
      # Set up Docker Buildx is a command used to set up Docker Buildx, which is a Docker CLI plugin for extended build capabilities with BuildKit.  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      #Docker build is a command used to create a Docker image from a Dockerfile and a context.
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/robinrobinson824:latest,${{ secrets.DOCKERHUB_USERNAME }}/robinrobinson824:02
          push: ${{ github.event_name != 'pull_request'}}
