---
name: 01 Basic Docker Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      # Set up Docker Buildx is a command used to set up Docker Buildx, which is a Docker CLI plugin for extended build capabilities with BuildKit.  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      #Docker build is a command used to create a Docker image from a Dockerfile and a context.
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          #push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/udemyexercise1:01
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
