name: 1 Basic Docker Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      # Set up QEMU is a command used to set up QEMU, which is a generic and open source machine emulator and virtualizer.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
          
      # Set up Docker Buildx is a command used to set up Docker Buildx, which is a Docker CLI plugin for extended build capabilities with BuildKit.  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker meta is a command used to generate metadata for Docker images, including tags and labels.
      # It uses the docker/metadata-action@v5 action to create metadata based on the provided configuration.

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/robinrobinson824
          flavor: |
            latest=false
          tags: |
            type=raw,value=02
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
      
      #Docker build is a command used to create a Docker image from a Dockerfile and a context.
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          # this is a list of platforms that QEMU will be set up for.